version: 2.1
#orbs:
#  python: circleci/python@0.2.1
jobs:
  build_and_test:
    #executor: python/default
    working_directory: ~/workspace
    docker:
      - image: circleci/python:latest
    #    restart: on-failure # Restart the container if it exits due to an error
    steps:
      - checkout
      #- python/load-cache
      #- python/install-deps
      #- python/save-cache      
      - setup_remote_docker:
          docker_layer_caching: false # Only available in paid plan      
      - run:
          name: Install dependencies
          command: |
            pipenv install
            python -m pytest --version
            python -m flask --version
      - run: 
          name: Run Tests
          command: |
            python -m pytest -v
      - run:
          name: Build docker image
          command: |
            docker build -t khteh/pythonflaskrestapi:latest src
workflows:
  main:
    jobs:
      - build_and_test